DROP DATABASE IF EXISTS MEETME;
CREATE DATABASE MEETME;
USE MEETME;

CREATE TABLE MEMBER
(
ID_MEMBER INT(9) NOT NULL PRIMARY KEY,
AGE TINYINT(2),
GENDER TINYINT(1),
IMGPROFILE VARCHAR(100),
BIO VARCHAR(200),
PASSWORD VARCHAR(20) NOT NULL
);

CREATE TABLE FRIEND
(
ID_MEMBER NOT NULL,
ID_FRIEND NOT NULL,
FOREIGN KEY (ID_MEMBER) REFERENCES MEMBER(ID_MEMBER)
);

/*
CREATE TABLE MESSAGE
(
ID_MESSAGE INT(9) NOT NULL PRIMARY KEY,
CONTENT VARCHAR(200) NOT NULL
);

CREATE TABLE CONVERSATION
(
ID_MEMBER INT(9) NOT NULL FOREIGN KEY REFERENCES (MEMBER),
ID_MESSAGE INT (9) FOREIGN KEY REFERENCES (MESSAGE)
);
*/

/*
 linux command line to connect to DB:
	mysql -h 127.0.0.1 -P 3306 -u root -p MEETME

 linux command line to launch createDB.sql
	mysql -u root -p < createDB.sql
*/
