DROP {DATABASE | SCHEMA} [IF EXISTS] MEETME;
CREATE DATABASE MEETME;

CREATE TABLE MEMBER
(
ID_MEMBER INT(9) NOT NULL PRIMARY KEY,
AGE TINYINT(2),
GENDER TINYINT(1),
IMGPROFILE VARCHAR(100),
BIO VARCHAR(200),
PASSWORD VARCHAR(20) NOT NULL
);

CREATE TABLE FRIEND
(
ID_MEMBER INT(9) NOT NULL FOREIGN KEY REFERENCES MEMBER,
ID_FRIEND INT(9) NOT NULL
);

CREATE TABLE MESSAGE
(
ID_MESSAGE INT(9) NOT NULL PRIMARY KEY,
CONTENT VARCHAR(200) NOT NULL
);

CREATE TABLE CONVERSATION
(
ID_MEMBER INT(9) NOT NULL FOREIGN KEY REFERENCES MEMBER,
ID_MESSAGE INT (9) FOREIGN KEY REFERENCES MESSAGE
);
